# Generated by Django 3.0.7 on 2020-06-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enseignant'), (2, 'Responsable module'), (3, 'Chef de departement'), (4, 'Administrateur')], default=1),
        ),
    ]
